name: Publish

on:
  push:
    branches:
      - master  # default branch

jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Standard usage
    - uses:  helaili/jekyll-action@v2
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Specify the Jekyll source location as a parameter
    - uses: helaili/jekyll-action@v2
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}

    # Specify the target branch (optional)
    - uses: helaili/jekyll-action@v2
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: 'gh-pages'
